services:
  churn-analytics-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: customer_churn_analytics
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data